name: PyTest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.3
          - 3.4
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - run: python -m pip install --upgrade pip
      - run: python -m pip install flake8 pytest
      - run: python -m pytest -v
      - run: flake8 .
